# Generated by Django 3.2.5 on 2021-07-30 20:57

import audio.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.CharField(max_length=100)),
                ('record', models.FileField(null=True, upload_to=audio.models.get_file_path)),
                ('record_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], default='Audio', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Transcribing', 'Transcribing'), ('Failed', 'Failed')], default='Pending', max_length=32)),
                ('result', models.TextField()),
            ],
        ),
    ]
