# Generated by Django 3.2.5 on 2021-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='model_chosen',
            field=models.CharField(choices=[('Jonatas-Short', 'Jonatas-Short'), ('Finetuned on MLLS-Long', 'Finetuned on MLLS-Long')], default='Jonatas-Short', max_length=100),
        ),
    ]
