# Generated by Django 3.2.5 on 2021-07-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_request_model_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='model_chosen',
        ),
    ]
