# Generated by Django 3.2.5 on 2021-08-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20210810_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='model_chosen',
            new_name='model_choosen',
        ),
    ]
